services:
  postgres:
    image: postgres:15
    container_name: prisma-postgres-local
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma_local
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
