name: Prod Database Migration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run Migrations
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          MIGRATION_NAME=$(echo "$COMMIT_MSG" | grep -oP "prod-deploy-\K[\w\-]+")
          if [ -n "$MIGRATION_NAME" ]; then
            npx prisma migrate deploy
          else
            echo "No prod-deploy-* migration trigger found in commit message. Skipping."
          fi
